server:
  port: 8088
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

users:
  msg: "Default profile"
  email: "kontakt@piotrsarnecki.com"  
springdoc:
  swagger-ui:
    path: "/swagger"
